import Head from 'next/head';
import styles from '../styles/Home.module.css';
import Search from '../components/search';

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

<h1>View more info about countries</h1>
      <Search />
    </div>
  );
}
